/**
 * Single source of truth for the vocabulary — the operator modules, the tests,
 * the migration tables, and docs pages derive from this array so they can
 * never drift.
 *
 * Every operator entry carries its 8-policy operator story:
 * Source → Trigger → Value → Cardinality → Time → Concurrency → Cancellation
 * → Termination. The story is the compressed behavior description; the
 * `behavior` line is its one-sentence summary.
 */

export type EntryKind = 'boundary' | 'root' | 'alias' | 'partial' | 'wrapper' | 'keep' | 'excluded';

export interface OperatorStory {
  readonly source: string;
  readonly trigger: string;
  readonly value: string;
  readonly cardinality: string;
  readonly time: string;
  readonly concurrency: string;
  readonly cancellation: string;
  readonly termination: string;
}

export interface CatalogEntry {
  /** Exported vocabulary name (for excluded entries: the official name). */
  readonly friendly: string;
  /** Official rxjs export this maps to; null for boundaries and roots. */
  readonly official: string | null;
  readonly family: string;
  readonly kind: EntryKind;
  /** Composed spelling, when the name is a named partial application. */
  readonly composed?: string;
  /** One-line behavior statement (for excluded entries: the replacement). */
  readonly behavior: string;
  /** 8-policy operator story; present on every operator entry. */
  readonly story?: OperatorStory;
}

export const catalog: readonly CatalogEntry[] = [
  // ————————————————————————————————————————————————————————————————————————
  // Boundary combinators — the suffixes as values (no story: they are values,
  // not operators)
  // ————————————————————————————————————————————————————————————————————————
  { friendly: 'time', official: null, family: 'boundary', kind: 'boundary', behavior: 'A fixed clock duration drives the boundary.' },
  { friendly: 'count', official: null, family: 'boundary', kind: 'boundary', behavior: 'A fixed number of values drives the boundary (reserved for boundaries; the rxjs aggregate is countOnComplete).' },
  { friendly: 'whileTrue', official: null, family: 'boundary', kind: 'boundary', behavior: 'Continue as long as the predicate holds.' },
  { friendly: 'until', official: null, family: 'boundary', kind: 'boundary', behavior: 'A notifier observable ends it — terminal, fires once.' },
  { friendly: 'on', official: null, family: 'boundary', kind: 'boundary', behavior: 'Act each time the notifier emits — repeating trigger.' },
  { friendly: 'when', official: null, family: 'boundary', kind: 'boundary', behavior: 'A factory you supply creates the boundary signal per cycle or per value.' },
  { friendly: 'toggle', official: null, family: 'boundary', kind: 'boundary', behavior: 'Act between explicit open and close signals.' },

  // ————————————————————————————————————————————————————————————————————————
  // Curried roots — dispatch on the boundary kind to the official operator
  // ————————————————————————————————————————————————————————————————————————
  {
    friendly: 'take', official: null, family: 'take', kind: 'root',
    behavior: 'Keep values as long as the boundary allows: count, whileTrue, until, time.',
    story: {
      source: 'Each source value flows into the operator.',
      trigger: 'Every source next is checked against the boundary: a count, a predicate, a notifier, or a timer.',
      value: 'Values are forwarded unchanged while the boundary allows.',
      cardinality: 'The result is a prefix of the source.',
      time: 'Forwarded values keep their source timing.',
      concurrency: 'No inner observable is created; until and time boundaries subscribe to one notifier.',
      cancellation: 'The source is cancelled as soon as the boundary closes.',
      termination: 'The result completes when the boundary closes or the source completes; errors are forwarded.',
    },
  },
  {
    friendly: 'skip', official: null, family: 'skip', kind: 'root',
    behavior: 'Drop values while the boundary holds: count, whileTrue, until, time.',
    story: {
      source: 'Each source value flows into the operator.',
      trigger: 'Every source next is checked against the boundary: a count, a predicate, a notifier, or a timer.',
      value: 'Values are dropped while the boundary holds, then forwarded unchanged.',
      cardinality: 'The result is a suffix of the source.',
      time: 'Forwarded values keep their source timing.',
      concurrency: 'No inner observable is created; until and time boundaries subscribe to one notifier.',
      cancellation: 'Nothing is cancelled; dropped values are simply not forwarded.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'buffer', official: null, family: 'buffer', kind: 'root',
    behavior: 'Collect values into arrays; flush per boundary: time, count, on, when, toggle.',
    story: {
      source: 'One source observable provides values; the boundary provides flush signals.',
      trigger: 'The boundary closes a collection cycle: a count is reached, a duration elapses, a signal emits, a created signal fires, or a close signal follows an open signal.',
      value: 'Source values are collected into an array and flushed at the cycle end.',
      cardinality: 'Many source values become one array per cycle.',
      time: 'The boundary controls flush timing.',
      concurrency: 'Toggle boundaries may keep several collections open at once; the others keep one.',
      cancellation: 'Unsubscribing drops the active collection.',
      termination: 'Errors are forwarded; on completion the active collection is flushed or dropped per the dispatched official operator.',
    },
  },
  {
    friendly: 'window', official: null, family: 'window', kind: 'root',
    behavior: 'Route values into inner observables; open and close per boundary: time, count, on, when, toggle.',
    story: {
      source: 'One source observable provides values; the boundary provides window boundaries.',
      trigger: 'The boundary closes the current window and opens the next one.',
      value: 'Source values are routed into an inner observable window.',
      cardinality: 'Many source values become one inner observable per cycle.',
      time: 'The boundary controls when windows open and close.',
      concurrency: 'Toggle and configured count/time boundaries may keep several windows open; the others keep one.',
      cancellation: 'Unsubscribing closes active windows.',
      termination: 'Active windows close on source completion; errors are forwarded.',
    },
  },
  {
    friendly: 'debounce', official: null, family: 'debounce', kind: 'root',
    behavior: 'Emit the latest value after silence: time (fixed) or when (per-value signal).',
    story: {
      source: 'Source values arrive over time.',
      trigger: "A value's silence period ends: the fixed duration elapses or the created signal fires.",
      value: 'The pending value is emitted only if no newer value replaced it.',
      cardinality: 'Many rapid values collapse to the latest surviving value.',
      time: 'The boundary defines the silence period per value.',
      concurrency: 'Only the latest pending value matters.',
      cancellation: 'A new source value cancels the previous pending emission.',
      termination: 'Completion emits the pending value if one is waiting; errors are forwarded.',
    },
  },
  {
    friendly: 'throttle', official: null, family: 'throttle', kind: 'root',
    behavior: 'Emit, then suppress during the window: time (fixed), when (per-value signal), or count (every nth value, leading).',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first allowed value opens a suppression window; the boundary closes it.',
      value: 'The allowed value is emitted; values during the window are dropped.',
      cardinality: 'Many rapid values become at most one per window.',
      time: 'The boundary defines the window: a fixed duration, a created signal, or a count of values.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Suppressed values are dropped, not buffered.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'audit', official: null, family: 'audit', kind: 'root',
    behavior: 'Suppress during the window, emit the latest when it closes: time or when.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first value opens a window; emission happens when the boundary closes it.',
      value: 'The latest value seen during the window is emitted at its close.',
      cardinality: 'Many values per window become at most one.',
      time: 'The boundary defines the window: a fixed duration or a created signal.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Older suppressed values are replaced by newer ones.',
      termination: 'Errors are forwarded; completion waits for the active window to settle.',
    },
  },
  {
    friendly: 'sample', official: null, family: 'sample', kind: 'root',
    behavior: 'Emit the latest value on a trigger: time (interval), on (signal), or count (every nth value, trailing).',
    story: {
      source: 'One source observable provides values; the boundary provides sampling ticks.',
      trigger: 'The boundary ticks: a fixed interval elapses, the signal emits, or every nth value arrives.',
      value: 'The latest source value since the last tick is emitted; nothing is emitted if no new value arrived.',
      cardinality: 'Many source values become at most one per tick.',
      time: 'The boundary controls output timing.',
      concurrency: 'Source and trigger are subscribed concurrently.',
      cancellation: 'Nothing is cancelled; only the latest value is remembered.',
      termination: 'Source error and completion are forwarded; no value is emitted on completion.',
    },
  },

  // ————————————————————————————————————————————————————————————————————————
  // Named partial applications — the two-word vocabulary
  // ————————————————————————————————————————————————————————————————————————
  {
    friendly: 'bufferOn', official: 'buffer', family: 'buffer', kind: 'partial',
    composed: 'buffer(on(signal$))',
    behavior: 'Flushes the collected array each time the signal emits.',
    story: {
      source: 'One source observable provides values; one notifier provides flush signals.',
      trigger: 'The notifier emits.',
      value: 'Collected source values are flushed as an array.',
      cardinality: 'Many source values become one array per signal.',
      time: 'The notifier controls flush timing.',
      concurrency: 'Source and notifier are subscribed concurrently.',
      cancellation: 'Unsubscribing clears the active collection.',
      termination: 'Errors from source or notifier are forwarded; completion ends the stream.',
    },
  },
  {
    friendly: 'windowOn', official: 'window', family: 'window', kind: 'partial',
    composed: 'window(on(signal$))',
    behavior: 'Closes the current window and opens a new one each time the signal emits.',
    story: {
      source: 'One source observable provides values; one notifier provides window boundaries.',
      trigger: 'The notifier emits.',
      value: 'The current window closes and a new inner observable window opens.',
      cardinality: 'Many source values become one inner observable per signal.',
      time: 'The notifier controls the window boundaries.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Unsubscribing closes the active window.',
      termination: 'The active window closes when the source completes; errors are forwarded.',
    },
  },
  {
    friendly: 'sampleOn', official: 'sample', family: 'sample', kind: 'partial',
    composed: 'sample(on(signal$))',
    behavior: 'Emits the latest source value each time the signal emits.',
    story: {
      source: 'One source observable provides values; a sampler provides snapshot signals.',
      trigger: 'The sampler emits.',
      value: 'The latest source value since the previous snapshot is emitted.',
      cardinality: 'Many source values become at most one per snapshot.',
      time: 'The sampler controls output timing.',
      concurrency: 'Source and sampler are subscribed concurrently.',
      cancellation: 'Nothing is cancelled; only the latest value is remembered.',
      termination: 'The result completes with the source; errors from source or sampler are forwarded.',
    },
  },
  {
    friendly: 'debounceWhen', official: 'debounce', family: 'debounce', kind: 'partial',
    composed: 'debounce(when(make))',
    behavior: 'Emits a value once the signal you create for it fires without a newer value arriving.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The signal created for a value fires before a newer value arrives.',
      value: 'The pending value is emitted if it survived its own silence signal.',
      cardinality: 'Many rapid values collapse to the latest surviving value.',
      time: 'Each value gets its own signal-controlled silence period.',
      concurrency: "Only the latest pending value's signal is active.",
      cancellation: 'A new source value cancels the previous pending emission and its signal.',
      termination: 'Completion emits the pending value if one is waiting; errors are forwarded.',
    },
  },
  {
    friendly: 'throttleWhen', official: 'throttle', family: 'throttle', kind: 'partial',
    composed: 'throttle(when(make))',
    behavior: 'Emits a value, then suppresses until the signal you created for it fires.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first allowed value opens a window that the created signal closes.',
      value: 'The allowed value is emitted; values during the window are dropped.',
      cardinality: 'Many rapid values become at most one per window.',
      time: "The created signal defines each window's length.",
      concurrency: 'One window is active at a time.',
      cancellation: 'Suppressed values are dropped, not buffered.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'auditWhen', official: 'audit', family: 'audit', kind: 'partial',
    composed: 'audit(when(make))',
    behavior: 'Suppresses while the signal you created runs, then emits the latest value.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first value opens a window that the created signal closes.',
      value: 'The latest value seen during the window is emitted when the signal fires.',
      cardinality: 'Many values per window become at most one.',
      time: "The created signal defines each window's length.",
      concurrency: 'One window is active at a time.',
      cancellation: 'Older suppressed values are replaced by newer ones.',
      termination: 'Errors are forwarded; completion waits for the active window to settle.',
    },
  },

  // ————————————————————————————————————————————————————————————————————————
  // Renamed aliases — pure re-exports
  // ————————————————————————————————————————————————————————————————————————
  {
    friendly: 'distinctFromPrevious', official: 'distinctUntilChanged', family: 'distinct', kind: 'alias',
    behavior: 'Drops only consecutive duplicates — compares with the previous value.',
    story: {
      source: 'Each source value flows with memory of the previous value.',
      trigger: 'Every source next compares the current value with the previous one.',
      value: 'Only values different from the immediately previous value are kept.',
      cardinality: 'The result is a subset of the source.',
      time: 'Kept values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'distinctFromPreviousBy', official: 'distinctUntilKeyChanged', family: 'distinct', kind: 'alias',
    behavior: 'Drops consecutive duplicates compared by a selected key.',
    story: {
      source: 'Each source object flows with memory of the previous key value.',
      trigger: 'Every source next compares the selected key with the previous key.',
      value: 'Values are kept only when the selected key changed.',
      cardinality: 'The result is a subset of the source.',
      time: 'Kept values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'ignoreValues', official: 'ignoreElements', family: 'filter', kind: 'alias',
    behavior: 'Drops all values but keeps error and completion.',
    story: {
      source: 'Source next, error, and complete notifications flow through the operator.',
      trigger: 'Every source notification is observed.',
      value: 'All next values are dropped.',
      cardinality: 'Many source values become zero output values.',
      time: 'Error and completion keep their timing.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'reduceOnComplete', official: 'reduce', family: 'aggregate', kind: 'alias',
    behavior: 'Folds all values; emits the single result when the source completes.',
    story: {
      source: 'Source values flow through an accumulator.',
      trigger: 'Every value updates the accumulator; source completion triggers output.',
      value: 'The accumulator function builds one final result.',
      cardinality: 'Many source values become one final value.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The result emits the final accumulator and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'countOnComplete', official: 'count', family: 'aggregate', kind: 'alias',
    behavior: 'Counts values; emits the total when the source completes.',
    story: {
      source: 'Source values are counted.',
      trigger: 'Source completion triggers the count result.',
      value: 'The total count is emitted as a number.',
      cardinality: 'Many source values become one number.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The result emits the count and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'maxOnComplete', official: 'max', family: 'aggregate', kind: 'alias',
    behavior: 'Emits the largest value when the source completes.',
    story: {
      source: 'Comparable source values are observed.',
      trigger: 'Source completion triggers the result.',
      value: 'The largest remembered value is emitted.',
      cardinality: 'Many source values become one maximum value.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The result emits the maximum and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'minOnComplete', official: 'min', family: 'aggregate', kind: 'alias',
    behavior: 'Emits the smallest value when the source completes.',
    story: {
      source: 'Comparable source values are observed.',
      trigger: 'Source completion triggers the result.',
      value: 'The smallest remembered value is emitted.',
      cardinality: 'Many source values become one minimum value.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The result emits the minimum and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'toArrayOnComplete', official: 'toArray', family: 'aggregate', kind: 'alias',
    behavior: 'Collects all values into one array; emits it when the source completes.',
    story: {
      source: 'All source values are collected.',
      trigger: 'Source completion triggers output.',
      value: 'The collected values are emitted as one array.',
      cardinality: 'Many source values become one array.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'Unsubscribing drops the collected values.',
      termination: 'The result emits the array and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'takeLastOnComplete', official: 'takeLast', family: 'take', kind: 'alias',
    behavior: 'Buffers the last N values; emits them when the source completes.',
    story: {
      source: 'Source values are stored in a trailing buffer of size N.',
      trigger: 'Source completion triggers output.',
      value: 'The final N values are emitted.',
      cardinality: 'Many source values become at most N final values.',
      time: 'Output happens only on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The result emits the buffered values and completes, or errors if the source errors.',
    },
  },
  {
    friendly: 'whenAllReady', official: 'forkJoin', family: 'join', kind: 'alias',
    behavior: 'Waits for all inputs to complete, then emits their last values once.',
    story: {
      source: 'Multiple input observables are observed together.',
      trigger: 'Output happens only when all inputs complete.',
      value: 'The last value of each input is combined into one result.',
      cardinality: 'Many streams produce one combined value.',
      time: 'Output happens at completion time.',
      concurrency: 'All inputs are subscribed concurrently.',
      cancellation: 'Unsubscribing cancels all input subscriptions.',
      termination: 'Emits once and completes after all inputs complete; errors if any input errors.',
    },
  },

  // ————————————————————————————————————————————————————————————————————————
  // Configured wrappers
  // ————————————————————————————————————————————————————————————————————————
  {
    friendly: 'shareLatest', official: 'shareReplay', family: 'share', kind: 'wrapper',
    composed: 'shareReplay({ bufferSize: 1, refCount: true })',
    behavior: 'Shares one subscription and replays the latest value to late subscribers.',
    story: {
      source: 'One cold source is shared among subscribers through a replay-1 subject.',
      trigger: 'The first subscriber starts the shared subscription; late subscribers trigger replay.',
      value: 'Notifications are multicast; the latest value is replayed to newcomers.',
      cardinality: 'One source subscription feeds many subscribers.',
      time: 'Late subscribers receive the latest value immediately, then live timing.',
      concurrency: 'One producer is shared by many observers.',
      cancellation: 'The source is unsubscribed when the subscriber count drops to zero.',
      termination: 'Error and completion are forwarded; the shared state resets once the subscriber count reaches zero.',
    },
  },

  // ————————————————————————————————————————————————————————————————————————
  // Kept official names — grammar-conform, re-exported unchanged by kept.ts
  // ————————————————————————————————————————————————————————————————————————
  {
    friendly: 'takeWhile', official: 'takeWhile', family: 'take', kind: 'keep',
    behavior: 'Keeps values while the predicate holds, then completes.',
    story: {
      source: 'Source values are checked in order.',
      trigger: 'Every value checks the predicate.',
      value: 'Values are forwarded while the predicate is true.',
      cardinality: 'The result is the source prefix while the condition holds.',
      time: 'Forwarded values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled when the predicate fails.',
      termination: 'Completes when the predicate fails or the source completes; errors are forwarded.',
    },
  },
  {
    friendly: 'takeUntil', official: 'takeUntil', family: 'take', kind: 'keep',
    behavior: 'Forwards values until the notifier emits, then completes.',
    story: {
      source: 'One source provides values; one notifier provides a stop signal.',
      trigger: 'The stop signal emits.',
      value: 'Source values are forwarded until the signal.',
      cardinality: 'The result is the source prefix before the signal.',
      time: 'The notifier controls when forwarding stops.',
      concurrency: 'Source and notifier are subscribed concurrently.',
      cancellation: 'The source is cancelled when the signal emits.',
      termination: 'Completes on the signal or source completion; errors from either are forwarded.',
    },
  },
  {
    friendly: 'skipWhile', official: 'skipWhile', family: 'skip', kind: 'keep',
    behavior: 'Drops values while the predicate holds, then forwards everything.',
    story: {
      source: 'Source values are checked in order.',
      trigger: 'Every value checks the predicate until it first fails.',
      value: 'Values are dropped while the predicate is true, then all later values are forwarded.',
      cardinality: 'The result is the source suffix after the first predicate failure.',
      time: 'Forwarded values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'skipUntil', official: 'skipUntil', family: 'skip', kind: 'keep',
    behavior: 'Drops values until the notifier emits, then forwards.',
    story: {
      source: 'One source provides values; one notifier provides a start signal.',
      trigger: 'The start signal emits.',
      value: 'Values before the signal are dropped; later values are forwarded.',
      cardinality: 'The result is the source suffix after the signal.',
      time: 'The notifier controls when forwarding begins.',
      concurrency: 'Source and notifier are subscribed concurrently.',
      cancellation: 'The notifier is unsubscribed once forwarding starts.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'skipLast', official: 'skipLast', family: 'skip', kind: 'keep',
    behavior: 'Forwards all but the final N values.',
    story: {
      source: 'Source values flow through a trailing buffer of size N.',
      trigger: 'A value is emitted once N later values have arrived.',
      value: 'Values are delayed through the buffer so the final N can be dropped.',
      cardinality: 'The result is the source minus its last N values.',
      time: 'Output is delayed by the trailing buffer.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'The buffered last N values are dropped on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'bufferTime', official: 'bufferTime', family: 'buffer', kind: 'keep',
    behavior: 'Collects values into arrays over fixed durations.',
    story: {
      source: 'One source provides values over time.',
      trigger: 'A fixed time window closes.',
      value: 'Values inside the window are collected into an array.',
      cardinality: 'Many values per window become one array.',
      time: 'Fixed-duration windows control flushing.',
      concurrency: 'Timers manage the active collections.',
      cancellation: 'Unsubscribing cancels timers and drops active collections.',
      termination: 'The active collection is flushed on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'bufferCount', official: 'bufferCount', family: 'buffer', kind: 'keep',
    behavior: 'Collects values into arrays of N.',
    story: {
      source: 'One source provides values.',
      trigger: 'The collection reaches the configured count.',
      value: 'Values are collected into an array.',
      cardinality: 'N source values become one array.',
      time: 'Flushing is count-based, not clock-based.',
      concurrency: 'No inner observable is created.',
      cancellation: 'Unsubscribing drops active collections.',
      termination: 'A partial collection is flushed on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'bufferToggle', official: 'bufferToggle', family: 'buffer', kind: 'keep',
    behavior: 'Collects values between open and close signals.',
    story: {
      source: 'One source provides values; one signal opens collections and a created signal closes them.',
      trigger: 'An open signal starts a collection; its close signal flushes it.',
      value: 'Values between open and close are collected into arrays.',
      cardinality: 'Many values per open-close pair become one array.',
      time: "Signals define each collection's lifetime.",
      concurrency: 'Several collections may be open at once.',
      cancellation: 'Unsubscribing discards active collections.',
      termination: 'Active collections are flushed on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'bufferWhen', official: 'bufferWhen', family: 'buffer', kind: 'keep',
    behavior: 'Collects values until a created closing signal fires.',
    story: {
      source: "One source provides values; a factory creates each cycle's closing signal.",
      trigger: 'The current closing signal emits.',
      value: 'Values are collected until the created signal fires, then flushed.',
      cardinality: 'Many values per cycle become one array.',
      time: 'The created signals control cycle timing.',
      concurrency: 'One collection is active at a time.',
      cancellation: 'Unsubscribing cancels the active closing signal.',
      termination: 'The active collection is flushed on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'windowTime', official: 'windowTime', family: 'window', kind: 'keep',
    behavior: 'Routes values into inner observable windows over fixed durations.',
    story: {
      source: 'One source provides values over time.',
      trigger: 'A fixed time window closes.',
      value: 'Values are routed into an inner observable window.',
      cardinality: 'Many values per duration become one window.',
      time: 'Fixed-duration timers control windows.',
      concurrency: 'Windows may overlap depending on configuration.',
      cancellation: 'Unsubscribing closes active windows and cancels timers.',
      termination: 'Active windows close on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'windowCount', official: 'windowCount', family: 'window', kind: 'keep',
    behavior: 'Routes values into inner observable windows of N.',
    story: {
      source: 'One source provides values.',
      trigger: 'The window reaches the configured count.',
      value: 'Values are routed into an inner observable window.',
      cardinality: 'N source values form one window.',
      time: 'Windowing is count-based, not clock-based.',
      concurrency: 'Windows may overlap when a start interval is configured.',
      cancellation: 'Unsubscribing closes active windows.',
      termination: 'Active windows close on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'windowToggle', official: 'windowToggle', family: 'window', kind: 'keep',
    behavior: 'Opens windows between open and close signals.',
    story: {
      source: 'One source provides values; one signal opens windows and a created signal closes them.',
      trigger: 'An open signal opens a window; its close signal closes it.',
      value: 'Values are routed into every window open at their arrival.',
      cardinality: 'Many values per open-close pair become one window.',
      time: "Signals define each window's lifetime.",
      concurrency: 'Several windows may be open at once.',
      cancellation: 'Unsubscribing closes active windows.',
      termination: 'Active windows close on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'windowWhen', official: 'windowWhen', family: 'window', kind: 'keep',
    behavior: 'Opens a window until a created closing signal fires, then the next.',
    story: {
      source: "One source provides values; a factory creates each window's closing signal.",
      trigger: 'The current closing signal emits.',
      value: 'Values are routed into the active window until the created signal fires.',
      cardinality: 'Many values per cycle become one window.',
      time: 'The created signals control window timing.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Unsubscribing cancels the active closing signal and closes the window.',
      termination: 'The active window closes on completion; errors are forwarded.',
    },
  },
  {
    friendly: 'debounceTime', official: 'debounceTime', family: 'debounce', kind: 'keep',
    behavior: 'Emits the latest value after a fixed silence.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'A fixed silence duration passes after a value.',
      value: 'The pending value is emitted after the silence.',
      cardinality: 'Many rapid values collapse to the latest surviving value.',
      time: 'A fixed duration controls the silence.',
      concurrency: 'Only the latest pending value matters.',
      cancellation: 'A new value cancels the previous pending emission.',
      termination: 'Completion emits the pending value if one is waiting; errors are forwarded.',
    },
  },
  {
    friendly: 'throttleTime', official: 'throttleTime', family: 'throttle', kind: 'keep',
    behavior: 'Emits a value, then suppresses for a fixed duration.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first allowed value opens a fixed suppression window.',
      value: 'The allowed value is emitted; later values in the window are dropped.',
      cardinality: 'At most one value per window.',
      time: 'A fixed duration controls the window.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Suppressed values are dropped, not buffered.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'auditTime', official: 'auditTime', family: 'audit', kind: 'keep',
    behavior: 'Suppresses for a fixed window, then emits the latest value.',
    story: {
      source: 'Source values arrive over time.',
      trigger: 'The first value opens a fixed window.',
      value: 'The latest value in the window is emitted at its close.',
      cardinality: 'At most one value per window.',
      time: 'A fixed duration controls the window.',
      concurrency: 'One window is active at a time.',
      cancellation: 'Older suppressed values are replaced by newer ones.',
      termination: 'Errors are forwarded; completion waits for active timing to settle.',
    },
  },
  {
    friendly: 'sampleTime', official: 'sampleTime', family: 'sample', kind: 'keep',
    behavior: 'Periodically emits the latest value.',
    story: {
      source: 'One source provides values over time.',
      trigger: 'A periodic timer ticks.',
      value: 'The latest value since the previous tick is emitted.',
      cardinality: 'At most one value per tick.',
      time: 'A fixed interval controls output timing.',
      concurrency: 'Source and timer run concurrently.',
      cancellation: 'Nothing is cancelled; only the latest value is remembered.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'delay', official: 'delay', family: 'timing', kind: 'keep',
    behavior: 'Shifts every value later by a fixed duration.',
    story: {
      source: 'Source values flow into a scheduler-based delay.',
      trigger: 'Each value schedules a later emission.',
      value: 'The same value is forwarded later.',
      cardinality: 'One value in, one delayed value out.',
      time: 'A fixed delay shifts delivery forward.',
      concurrency: 'Scheduled timers may overlap.',
      cancellation: 'Unsubscribing cancels scheduled emissions.',
      termination: 'Completion is delayed until scheduled values flush; errors are forwarded immediately.',
    },
  },
  {
    friendly: 'delayWhen', official: 'delayWhen', family: 'timing', kind: 'keep',
    behavior: 'Delays each value until its own signal fires.',
    story: {
      source: 'Each source value gets its own delay signal.',
      trigger: 'The per-value delay signal emits.',
      value: 'The original value is forwarded after its signal.',
      cardinality: 'One value in, one delayed value out.',
      time: 'Each value has signal-controlled timing.',
      concurrency: 'Multiple delay signals may be active at once.',
      cancellation: 'Unsubscribing cancels pending delayed values.',
      termination: 'Completes after the source and pending delays finish; errors are forwarded.',
    },
  },
  {
    friendly: 'timeout', official: 'timeout', family: 'timing', kind: 'keep',
    behavior: 'Errors (or falls back) if the source is too slow.',
    story: {
      source: 'One source is watched by a deadline policy.',
      trigger: 'The deadline fires before the required emission.',
      value: 'A timeout error is raised, or the configured fallback takes over.',
      cardinality: 'Source values pass through until the deadline hits.',
      time: 'The configured deadline controls failure timing.',
      concurrency: 'Source and deadline timer run concurrently.',
      cancellation: 'The timer resets on each emission.',
      termination: 'Errors on timeout; otherwise follows source error and completion.',
    },
  },
  {
    friendly: 'distinct', official: 'distinct', family: 'distinct', kind: 'keep',
    behavior: 'Emits only values never seen before in the whole stream.',
    story: {
      source: 'Each value flows with memory of all previously seen values.',
      trigger: 'Every source next checks the seen-value store.',
      value: 'Only values never seen before are kept.',
      cardinality: 'The result is a subset of the source.',
      time: 'Kept values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'filter', official: 'filter', family: 'filter', kind: 'keep',
    behavior: 'Lets only matching values through.',
    story: {
      source: 'Each source value flows into the predicate.',
      trigger: 'Every source next checks the predicate.',
      value: 'Values that satisfy the predicate are kept.',
      cardinality: 'One source value produces one result value or none.',
      time: 'Kept values are emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'first', official: 'first', family: 'filter', kind: 'keep',
    behavior: 'Emits the first (matching) value, then completes.',
    story: {
      source: 'Source values are searched from the beginning.',
      trigger: 'The first value, or first matching value, arrives.',
      value: 'That value is emitted.',
      cardinality: 'Many source values produce one value.',
      time: 'Output happens immediately at the first match.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled after the match.',
      termination: 'Completes after the match; errors, or uses the default, if none exists.',
    },
  },
  {
    friendly: 'last', official: 'last', family: 'filter', kind: 'keep',
    behavior: 'Emits the final (matching) value on completion.',
    story: {
      source: 'Source values are remembered until completion.',
      trigger: 'Source completion triggers final selection.',
      value: 'The last value, or last matching value, is emitted.',
      cardinality: 'Many source values produce one final value.',
      time: 'Output happens only when the source completes.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Completes after emitting; errors, or uses the default, if no match exists.',
    },
  },
  {
    friendly: 'single', official: 'single', family: 'filter', kind: 'keep',
    behavior: 'Requires exactly one matching value, errors otherwise.',
    story: {
      source: 'Source values are checked against an optional predicate.',
      trigger: 'Matches are counted until completion or a second match appears.',
      value: 'The one matching value is emitted.',
      cardinality: 'Exactly one result value is required.',
      time: 'Output happens at completion, or an error happens earlier.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled early when a second match appears.',
      termination: 'Completes after the single match; errors on zero or multiple matches.',
    },
  },
  {
    friendly: 'find', official: 'find', family: 'filter', kind: 'keep',
    behavior: 'Emits the first value satisfying the predicate.',
    story: {
      source: 'Source values are searched with a predicate.',
      trigger: 'The first matching value or source completion decides the result.',
      value: 'The first matching value is emitted, or undefined if none exists.',
      cardinality: 'Many source values produce at most one value.',
      time: 'A match emits immediately; no match resolves on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled after the first match.',
      termination: 'Completes after the match or completion; errors are forwarded.',
    },
  },
  {
    friendly: 'findIndex', official: 'findIndex', family: 'filter', kind: 'keep',
    behavior: 'Emits the index of the first match.',
    story: {
      source: 'Indexed source values are searched with a predicate.',
      trigger: 'The first matching value or source completion decides the result.',
      value: 'The index of the first matching value is emitted, or -1 if none exists.',
      cardinality: 'Many source values produce one index value.',
      time: 'A matching index emits immediately; no match resolves on completion.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled after the first match.',
      termination: 'Completes after emitting the index; errors are forwarded.',
    },
  },
  {
    friendly: 'elementAt', official: 'elementAt', family: 'filter', kind: 'keep',
    behavior: 'Emits the value at the given index.',
    story: {
      source: 'Source values are treated as indexed emissions.',
      trigger: 'The requested index arrives.',
      value: 'Only the value at the requested index is emitted.',
      cardinality: 'Many source values produce at most one value.',
      time: 'The value is emitted when its index is reached.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The source is cancelled after the selected value.',
      termination: 'Completes after the value; errors, or uses the default, if the index is never reached.',
    },
  },
  {
    friendly: 'map', official: 'map', family: 'transform', kind: 'keep',
    behavior: 'Transforms each value.',
    story: {
      source: 'Each source value flows into the operator.',
      trigger: 'Every source next activates the projection function.',
      value: 'The projection transforms the value.',
      cardinality: 'One source value produces one result value.',
      time: 'The result is emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'scan', official: 'scan', family: 'transform', kind: 'keep',
    behavior: 'Emits the running accumulator state for every value.',
    story: {
      source: 'Each value flows with remembered accumulator state.',
      trigger: 'Every source next runs the accumulator function.',
      value: 'The accumulator state is updated.',
      cardinality: 'One source value produces one new state value.',
      time: 'The new state is emitted immediately.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'pairwise', official: 'pairwise', family: 'transform', kind: 'keep',
    behavior: 'Emits [previous, current] pairs.',
    story: {
      source: 'Values flow with memory of the previous value.',
      trigger: 'Each source next after the first triggers output.',
      value: 'The previous and current values are paired.',
      cardinality: 'Two adjacent source values produce one pair.',
      time: 'The pair is emitted immediately when the current value arrives.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded.',
    },
  },
  {
    friendly: 'groupBy', official: 'groupBy', family: 'transform', kind: 'keep',
    behavior: 'Splits the stream into keyed substreams.',
    story: {
      source: 'Each value carries or produces a grouping key.',
      trigger: 'Every source next computes or reads the key.',
      value: 'The value is routed into the grouped observable for its key.',
      cardinality: 'One value goes into one group; each new key creates a grouped observable.',
      time: 'Groups are created and values are routed immediately.',
      concurrency: 'Many grouped observables can be active at once.',
      cancellation: 'Group lifetimes end by unsubscription or configuration.',
      termination: 'Groups complete when the source completes and error when it errors.',
    },
  },
  {
    friendly: 'concatMap', official: 'concatMap', family: 'flatten', kind: 'keep',
    behavior: 'Maps to inner observables and runs them one after another (queue).',
    story: {
      source: 'Each source value is used to create inner work.',
      trigger: 'Every source next calls the projection function.',
      value: 'The value is mapped to an inner observable.',
      cardinality: 'One source value may produce many inner values.',
      time: 'Inner observables define result timing.',
      concurrency: 'Inner observables are queued; only one runs at a time.',
      cancellation: 'New source values never cancel the active inner observable; they wait.',
      termination: 'Completes after the source, the queue, and the active inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'mergeMap', official: 'mergeMap', family: 'flatten', kind: 'keep',
    behavior: 'Maps to inner observables and runs them concurrently.',
    story: {
      source: 'Each source value is used to create inner work.',
      trigger: 'Every source next calls the projection function.',
      value: 'The value is mapped to an inner observable.',
      cardinality: 'One source value may produce many inner values.',
      time: 'Inner observables define result timing.',
      concurrency: 'Multiple inner observables may run at once, optionally capped by a concurrency limit.',
      cancellation: 'New source values never cancel previous inner work.',
      termination: 'Completes after the source and all active inner observables complete; errors terminate the result.',
    },
  },
  {
    friendly: 'switchMap', official: 'switchMap', family: 'flatten', kind: 'keep',
    behavior: 'Maps to inner observables, cancelling the previous one (keep latest).',
    story: {
      source: 'Each source value is used to create inner work.',
      trigger: 'Every source next calls the projection function.',
      value: 'The value is mapped to an inner observable.',
      cardinality: 'One source value may produce many inner values.',
      time: 'The latest inner observable defines output timing.',
      concurrency: 'Only the latest inner observable is active.',
      cancellation: 'A new source value cancels the previous inner subscription.',
      termination: 'Completes after the source and the latest inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'exhaustMap', official: 'exhaustMap', family: 'flatten', kind: 'keep',
    behavior: 'Maps to inner observables, ignoring new values while busy.',
    story: {
      source: 'Each source value may create inner work.',
      trigger: 'A source next is accepted only when no inner observable is active.',
      value: 'Accepted values are mapped to inner observables.',
      cardinality: 'Accepted source values may produce many inner values.',
      time: 'The active inner observable defines output timing.',
      concurrency: 'Only one inner observable may be active.',
      cancellation: 'New source values are ignored while busy; nothing is cancelled.',
      termination: 'Completes after the source and the active inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'concatAll', official: 'concatAll', family: 'flatten', kind: 'keep',
    behavior: 'Flattens inner observables sequentially.',
    story: {
      source: 'A higher-order source emits inner observables.',
      trigger: 'An inner observable is subscribed when the previous one completes.',
      value: 'Inner values are forwarded sequentially.',
      cardinality: 'Many inner streams become one output stream.',
      time: 'The active inner observable controls timing.',
      concurrency: 'Only one inner observable is active at a time.',
      cancellation: 'New inner observables wait; nothing is cancelled.',
      termination: 'Completes after the outer source and all queued inners complete; errors terminate the result.',
    },
  },
  {
    friendly: 'mergeAll', official: 'mergeAll', family: 'flatten', kind: 'keep',
    behavior: 'Flattens inner observables concurrently.',
    story: {
      source: 'A higher-order source emits inner observables.',
      trigger: 'Every outer next subscribes to that inner observable.',
      value: 'Values from all active inners are forwarded.',
      cardinality: 'Many inner streams become one interleaved output stream.',
      time: 'Each inner observable controls the timing of its own values.',
      concurrency: 'Multiple inner observables may be active at once.',
      cancellation: 'New inner observables never cancel previous ones.',
      termination: 'Completes after the outer source and all active inners complete; errors terminate the result.',
    },
  },
  {
    friendly: 'switchAll', official: 'switchAll', family: 'flatten', kind: 'keep',
    behavior: 'Flattens by always switching to the latest inner observable.',
    story: {
      source: 'A higher-order source emits inner observables.',
      trigger: 'Every outer next switches to that latest inner observable.',
      value: 'Only values from the latest inner observable are forwarded.',
      cardinality: 'Many inner streams become one latest-only output stream.',
      time: 'The latest inner observable controls output timing.',
      concurrency: 'Only the latest inner observable is active.',
      cancellation: 'A new inner observable cancels the previous inner subscription.',
      termination: 'Completes after the outer source and the latest inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'exhaustAll', official: 'exhaustAll', family: 'flatten', kind: 'keep',
    behavior: 'Flattens the first inner observable, ignoring others while busy.',
    story: {
      source: 'A higher-order source emits inner observables.',
      trigger: 'An outer next is accepted only when no inner is active.',
      value: 'Accepted inner values are forwarded.',
      cardinality: 'Only accepted inner observables produce output.',
      time: 'The active inner observable controls output timing.',
      concurrency: 'Only one inner observable is active.',
      cancellation: 'New inner observables are ignored while busy.',
      termination: 'Completes after the outer source and the active inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'mergeScan', official: 'mergeScan', family: 'flatten', kind: 'keep',
    behavior: 'Accumulates state through overlapping async updates.',
    story: {
      source: 'Each value and the current state feed an asynchronous accumulator.',
      trigger: 'Every source next starts an accumulator inner observable.',
      value: 'The inner observable emits new state values.',
      cardinality: 'One source value may produce many state values.',
      time: 'Inner state observables define result timing.',
      concurrency: 'Accumulator inner observables may overlap.',
      cancellation: 'New source values never cancel previous accumulator work.',
      termination: 'Completes after the source and all active accumulator observables complete; errors terminate the result.',
    },
  },
  {
    friendly: 'switchScan', official: 'switchScan', family: 'flatten', kind: 'keep',
    behavior: 'Accumulates state; only the latest async update survives.',
    story: {
      source: 'Each value and the current state feed an asynchronous accumulator.',
      trigger: 'Every source next starts a new accumulator inner observable.',
      value: 'The accumulator maps state and value to an inner observable of state.',
      cardinality: 'One source value may produce many state values.',
      time: 'The latest accumulator inner observable defines result timing.',
      concurrency: 'Only the latest accumulator inner observable is active.',
      cancellation: 'A new source value cancels the previous accumulator inner observable.',
      termination: 'Completes after the source and the latest inner complete; errors terminate the result.',
    },
  },
  {
    friendly: 'expand', official: 'expand', family: 'flatten', kind: 'keep',
    behavior: 'Recursively feeds produced values back into the projection.',
    story: {
      source: 'Source values and generated values both feed the expansion.',
      trigger: 'Each emitted value triggers the recursive projection function.',
      value: 'The value is mapped to an observable whose values are expanded again.',
      cardinality: 'One value can recursively produce many more values.',
      time: 'Source and generated inner observables define timing.',
      concurrency: 'Recursive inner observables overlap up to the concurrency limit.',
      cancellation: 'Unsubscribing cancels all active recursive work.',
      termination: 'Completes when the source and all expansions complete; errors terminate the result.',
    },
  },
  {
    friendly: 'startWith', official: 'startWith', family: 'join', kind: 'keep',
    behavior: 'Prepends initial values.',
    story: {
      source: 'Initial values are placed before the source observable.',
      trigger: 'Subscription emits the initial values first.',
      value: 'Initial values are prepended to the source values.',
      cardinality: 'The result contains the initial values plus the source values.',
      time: 'Initial values emit synchronously on subscribe, then source timing takes over.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Source error and completion are forwarded after the initial values.',
    },
  },
  {
    friendly: 'endWith', official: 'endWith', family: 'join', kind: 'keep',
    behavior: 'Appends final values on completion.',
    story: {
      source: 'Final values are placed after the source observable.',
      trigger: 'Source completion emits the appended values.',
      value: 'Final values are appended to the source values.',
      cardinality: 'The result contains the source values plus the final values.',
      time: 'Appended values emit at completion time.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Completes after the appended values; an error skips them.',
    },
  },
  {
    friendly: 'withLatestFrom', official: 'withLatestFrom', family: 'join', kind: 'keep',
    behavior: 'Pairs each primary value with the latest values of other streams.',
    story: {
      source: 'One primary source combines with secondary observables.',
      trigger: 'Only the primary source emitting triggers output.',
      value: 'The primary value is paired with the latest secondary values.',
      cardinality: 'One primary value produces one combined value once all secondaries have emitted.',
      time: 'The primary source controls output timing.',
      concurrency: 'Primary and secondaries are subscribed concurrently.',
      cancellation: 'Secondary values are only remembered, never cancelled.',
      termination: 'Completes with the primary source; errors from any input are forwarded.',
    },
  },
  {
    friendly: 'catchError', official: 'catchError', family: 'error', kind: 'keep',
    behavior: 'Replaces a failed stream with a recovery observable.',
    story: {
      source: 'One source may emit values or fail.',
      trigger: 'A source error activates the recovery function.',
      value: 'The error is replaced by a recovery observable, or rethrown.',
      cardinality: 'One error may become many recovery values.',
      time: 'The recovery observable defines timing after the error.',
      concurrency: 'Recovery starts only after the failure.',
      cancellation: 'Unsubscribing cancels the recovery observable.',
      termination: 'Continues with the recovery stream, or terminates if the error is rethrown.',
    },
  },
  {
    friendly: 'retry', official: 'retry', family: 'error', kind: 'keep',
    behavior: 'Resubscribes after errors per the retry policy.',
    story: {
      source: 'One source may fail.',
      trigger: 'An error triggers resubscription while the retry policy allows it.',
      value: 'The same source execution is attempted again.',
      cardinality: 'Values may come from several attempts.',
      time: 'Retry timing is immediate or configured via the delay option.',
      concurrency: 'Only one attempt runs at a time.',
      cancellation: 'Unsubscribing cancels the current attempt and prevents future retries.',
      termination: 'Completes when an attempt completes; errors when retries are exhausted.',
    },
  },
  {
    friendly: 'tap', official: 'tap', family: 'utility', kind: 'keep',
    behavior: 'Runs side effects without changing the stream.',
    story: {
      source: 'Source next, error, and complete notifications pass through the operator.',
      trigger: 'Each observed notification runs the side-effect handler.',
      value: 'The original value is forwarded unchanged.',
      cardinality: 'One input notification produces one output notification.',
      time: 'Side effects run during notification delivery.',
      concurrency: 'No inner observable is created.',
      cancellation: 'No inner work exists to cancel.',
      termination: 'Error and completion are forwarded, unless the side effect throws.',
    },
  },
  {
    friendly: 'finalize', official: 'finalize', family: 'utility', kind: 'keep',
    behavior: 'Runs a callback on completion, error, or unsubscribe.',
    story: {
      source: 'Notifications pass through unchanged.',
      trigger: 'Teardown happens: completion, error, or unsubscription.',
      value: 'Values are untouched; the callback runs on teardown.',
      cardinality: 'The result has the same values as the source.',
      time: 'The callback runs exactly once, at teardown time.',
      concurrency: 'No inner observable is created.',
      cancellation: 'The callback also runs when the subscriber unsubscribes.',
      termination: 'Error and completion are forwarded; the callback observes every way the stream ends.',
    },
  },
  {
    friendly: 'share', official: 'share', family: 'share', kind: 'keep',
    behavior: 'Shares one subscription among all subscribers.',
    story: {
      source: 'One cold source is shared among subscribers.',
      trigger: 'The first subscriber starts the shared subscription.',
      value: 'Notifications are multicast to all current subscribers.',
      cardinality: 'One source subscription feeds many subscribers.',
      time: 'Subscribers share the live source timing.',
      concurrency: 'One producer is shared by many observers.',
      cancellation: 'The source is unsubscribed when the subscriber count drops to zero, per configuration.',
      termination: 'Error, completion, and reset behavior follow the share configuration.',
    },
  },

  // ————————————————————————————————————————————————————————————————————————
  // Excluded — deprecated in RxJS 7/8; the vocabulary teaches the replacement
  // ————————————————————————————————————————————————————————————————————————
  { friendly: 'retryWhen', official: 'retryWhen', family: 'error', kind: 'excluded', behavior: 'Use retry({ delay }).' },
  { friendly: 'repeatWhen', official: 'repeatWhen', family: 'repeat', kind: 'excluded', behavior: 'Use repeat({ delay }).' },
  { friendly: 'timeoutWith', official: 'timeoutWith', family: 'timing', kind: 'excluded', behavior: 'Use timeout({ with }).' },
  { friendly: 'mapTo', official: 'mapTo', family: 'transform', kind: 'excluded', behavior: 'Use map(() => value).' },
  { friendly: 'pluck', official: 'pluck', family: 'transform', kind: 'excluded', behavior: 'Use map with property access.' },
  { friendly: 'concatMapTo', official: 'concatMapTo', family: 'flatten', kind: 'excluded', behavior: 'Use concatMap(() => inner$).' },
  { friendly: 'mergeMapTo', official: 'mergeMapTo', family: 'flatten', kind: 'excluded', behavior: 'Use mergeMap(() => inner$).' },
  { friendly: 'switchMapTo', official: 'switchMapTo', family: 'flatten', kind: 'excluded', behavior: 'Use switchMap(() => inner$).' },
  { friendly: 'publish', official: 'publish', family: 'share', kind: 'excluded', behavior: 'Use share or connectable.' },
  { friendly: 'publishBehavior', official: 'publishBehavior', family: 'share', kind: 'excluded', behavior: 'Use share with a BehaviorSubject connector.' },
  { friendly: 'publishLast', official: 'publishLast', family: 'share', kind: 'excluded', behavior: 'Use share with an AsyncSubject connector.' },
  { friendly: 'publishReplay', official: 'publishReplay', family: 'share', kind: 'excluded', behavior: 'Use share with a ReplaySubject connector, or shareReplay.' },
  { friendly: 'multicast', official: 'multicast', family: 'share', kind: 'excluded', behavior: 'Use share with a connector.' },
  { friendly: 'refCount', official: 'refCount', family: 'share', kind: 'excluded', behavior: 'Use share({ resetOnRefCountZero }).' },
  { friendly: 'toPromise', official: 'toPromise', family: 'interop', kind: 'excluded', behavior: 'Use firstValueFrom or lastValueFrom.' },
];

/** Official names kept as-is and re-exported by `kept.ts` — derived, so the catalog stays the single source of truth. */
export const keptOfficialNames: readonly string[] = catalog
  .filter((e) => e.kind === 'keep')
  .map((e) => e.friendly);
