import { catalog } from './catalog';

/**
 * ESLint preset derived from the catalog — a `no-restricted-imports`
 * configuration that nudges teaching samples toward the vocabulary:
 *
 * - officials the vocabulary renames (partials and aliases) point to the
 *   friendly name,
 * - `shareReplay` points to `shareLatest` for the pinned configuration,
 * - excluded (deprecated) operators point to their modern replacement.
 *
 * Kept names (`takeUntil`, `map`, `concatMap`, …) are not restricted.
 * Regenerate the preset file with `npm run generate:lint`.
 */

export type LintSeverity = 'error' | 'warn';

export interface RestrictedImportPath {
  readonly name: 'rxjs';
  readonly importNames: readonly [string];
  readonly message: string;
}

export function restrictedImportPaths(): readonly RestrictedImportPath[] {
  const paths: RestrictedImportPath[] = [];
  for (const e of catalog) {
    if (e.official === null) continue;
    switch (e.kind) {
      case 'partial':
      case 'alias':
        paths.push({
          name: 'rxjs',
          importNames: [e.official],
          message: `Renamed in the rxjs-friendly vocabulary: use ${e.friendly}${
            e.composed ? ` (composed: ${e.composed})` : ''
          }.`,
        });
        break;
      case 'wrapper':
        paths.push({
          name: 'rxjs',
          importNames: [e.official],
          message: `Prefer ${e.friendly}() from rxjs-friendly (${e.composed ?? ''}); otherwise configure share().`,
        });
        break;
      case 'excluded':
        paths.push({
          name: 'rxjs',
          importNames: [e.official],
          message: `Deprecated in RxJS. ${e.behavior}`,
        });
        break;
      default:
        break;
    }
  }
  return paths;
}

export interface RxjsFriendlyLintConfig {
  readonly name: string;
  readonly rules: {
    readonly 'no-restricted-imports': readonly [
      LintSeverity,
      { readonly paths: readonly RestrictedImportPath[] },
    ];
  };
}

/** Flat-config object to compose into an `eslint.config.mjs`. */
export function rxjsFriendlyLintConfig(severity: LintSeverity = 'error'): RxjsFriendlyLintConfig {
  return {
    name: 'rxjs-friendly/vocabulary',
    rules: {
      'no-restricted-imports': [severity, { paths: restrictedImportPaths() }],
    },
  };
}

/** Renders the self-contained preset file `lint/rxjs-friendly-preset.mjs`. */
export function renderLintPreset(): string {
  const lines = [
    '// Generated by rxjs-friendly `npm run generate:lint` - do not edit.',
    '// ESLint flat-config preset: restricts `rxjs` imports that the vocabulary',
    '// renames or excludes. Compose it into eslint.config.mjs, e.g.:',
    "//   import rxjsFriendly from 'rxjs-friendly/lint/rxjs-friendly-preset.mjs';",
    "//   export default [{ ...rxjsFriendly, files: ['samples/**/*.ts'] }];",
    '// (TypeScript sources additionally need the typescript-eslint parser.)',
    '',
    `const paths = ${JSON.stringify(restrictedImportPaths(), null, 2)};`,
    '',
    'export default {',
    "  name: 'rxjs-friendly/vocabulary',",
    '  rules: {',
    "    'no-restricted-imports': ['error', { paths }],",
    '  },',
    '};',
    '',
  ];
  return lines.join('\n');
}
